#ifndef ABSTRACTOBJECTMODEL_GLOBAL_H
#define ABSTRACTOBJECTMODEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ABSTRACTOBJECTMODEL_LIBRARY)
#define ABSTRACTOBJECTMODEL_EXPORT Q_DECL_EXPORT
#else
#define ABSTRACTOBJECTMODEL_EXPORT Q_DECL_IMPORT
#endif

#endif // ABSTRACTOBJECTMODEL_GLOBAL_H
